
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10101:8080"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Host=db;Port=5432;Database=budgetbuddy;Username=postgres;Password=postgres
    volumes:
      - ./data-protection:/root/.aspnet/DataProtection-Keys

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: budgetbuddy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "10102:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: