// <auto-generated />
using System;
using BudgetBuddyAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BudgetBuddyAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260427192627_swdssdfedsdfsddf")]
    partial class swdssdfedsdfsddf
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("BankConnection", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("access_token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("TEXT");

                    b.Property<int>("institution_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("item_id")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("transactions_cursor")
                        .HasColumnType("TEXT");

                    b.Property<string>("user_id")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("institution_id");

                    b.HasIndex("user_id", "item_id")
                        .IsUnique();

                    b.ToTable("BankConnections");
                });

            modelBuilder.Entity("BudgetBuddyAPI.BankAccount", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("account_id")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("bank_connection_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("holder_category")
                        .HasColumnType("TEXT");

                    b.Property<string>("mask")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("official_name")
                        .HasColumnType("TEXT");

                    b.Property<string>("subtype")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("bank_connection_id", "account_id")
                        .IsUnique();

                    b.ToTable("BankAccounts");
                });

            modelBuilder.Entity("Institution", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("country_codes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("institution_id")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("products")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("institution_id")
                        .IsUnique();

                    b.ToTable("Institutions");
                });

            modelBuilder.Entity("Transaction", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("account_id")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("authorized_date")
                        .HasColumnType("TEXT");

                    b.Property<int>("bank_account_id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("date")
                        .HasColumnType("TEXT");

                    b.Property<string>("iso_currency_code")
                        .HasColumnType("TEXT");

                    b.Property<string>("logo_url")
                        .HasColumnType("TEXT");

                    b.Property<string>("merchant_name")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("payment_channel")
                        .HasColumnType("TEXT");

                    b.Property<bool>("pending")
                        .HasColumnType("INTEGER");

                    b.Property<string>("transaction_id")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("transaction_type")
                        .HasColumnType("TEXT");

                    b.Property<string>("website")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("bank_account_id");

                    b.HasIndex("transaction_id")
                        .IsUnique();

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("BankConnection", b =>
                {
                    b.HasOne("Institution", "institution")
                        .WithMany("bank_connections")
                        .HasForeignKey("institution_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("institution");
                });

            modelBuilder.Entity("BudgetBuddyAPI.BankAccount", b =>
                {
                    b.HasOne("BankConnection", "bank_connection")
                        .WithMany("accounts")
                        .HasForeignKey("bank_connection_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("AccountBalances", "balances", b1 =>
                        {
                            b1.Property<int>("BankAccountid")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal?>("available")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("current")
                                .HasColumnType("TEXT");

                            b1.Property<string>("iso_currency_code")
                                .HasColumnType("TEXT");

                            b1.Property<decimal?>("limit")
                                .HasColumnType("TEXT");

                            b1.Property<string>("unofficial_currency_code")
                                .HasColumnType("TEXT");

                            b1.HasKey("BankAccountid");

                            b1.ToTable("BankAccounts");

                            b1.WithOwner()
                                .HasForeignKey("BankAccountid");
                        });

                    b.Navigation("balances")
                        .IsRequired();

                    b.Navigation("bank_connection");
                });

            modelBuilder.Entity("Transaction", b =>
                {
                    b.HasOne("BudgetBuddyAPI.BankAccount", "bank_account")
                        .WithMany("transactions")
                        .HasForeignKey("bank_account_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BudgetBuddyAPI.Src.DB.PersonalFinanceCategory", "personal_finance_category", b1 =>
                        {
                            b1.Property<int>("Transactionid")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("confidence_level")
                                .HasColumnType("TEXT");

                            b1.Property<string>("detailed")
                                .HasColumnType("TEXT");

                            b1.Property<string>("primary")
                                .HasColumnType("TEXT");

                            b1.HasKey("Transactionid");

                            b1.ToTable("Transactions");

                            b1.WithOwner()
                                .HasForeignKey("Transactionid");
                        });

                    b.OwnsMany("TransactionCounterparty", "counterparties", b1 =>
                        {
                            b1.Property<int>("Transactionid")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("confidence_level")
                                .HasColumnType("TEXT");

                            b1.Property<string>("entity_id")
                                .HasColumnType("TEXT");

                            b1.Property<string>("logo_url")
                                .HasColumnType("TEXT");

                            b1.Property<string>("name")
                                .HasColumnType("TEXT");

                            b1.Property<string>("phone_number")
                                .HasColumnType("TEXT");

                            b1.Property<string>("type")
                                .HasColumnType("TEXT");

                            b1.Property<string>("website")
                                .HasColumnType("TEXT");

                            b1.HasKey("Transactionid", "Id");

                            b1.ToTable("TransactionCounterparty");

                            b1.WithOwner()
                                .HasForeignKey("Transactionid");
                        });

                    b.Navigation("bank_account");

                    b.Navigation("counterparties");

                    b.Navigation("personal_finance_category");
                });

            modelBuilder.Entity("BankConnection", b =>
                {
                    b.Navigation("accounts");
                });

            modelBuilder.Entity("BudgetBuddyAPI.BankAccount", b =>
                {
                    b.Navigation("transactions");
                });

            modelBuilder.Entity("Institution", b =>
                {
                    b.Navigation("bank_connections");
                });
#pragma warning restore 612, 618
        }
    }
}
