// <auto-generated />
using System;
using BudgetBuddyAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BudgetBuddyAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260501201300_swdssdfeddsdfss")]
    partial class swdssdfeddsdfss
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BankConnection", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("access_token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("institution_id")
                        .HasColumnType("integer");

                    b.Property<string>("item_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("transactions_cursor")
                        .HasColumnType("text");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("institution_id");

                    b.HasIndex("user_id", "item_id")
                        .IsUnique();

                    b.ToTable("BankConnections");
                });

            modelBuilder.Entity("BudgetBuddyAPI.BankAccount", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("account_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("bank_connection_id")
                        .HasColumnType("integer");

                    b.Property<string>("holder_category")
                        .HasColumnType("text");

                    b.Property<string>("mask")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("official_name")
                        .HasColumnType("text");

                    b.Property<string>("subtype")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("bank_connection_id", "account_id")
                        .IsUnique();

                    b.ToTable("BankAccounts");
                });

            modelBuilder.Entity("BudgetBuddyAPI.TransactionLocation", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("address")
                        .HasColumnType("text");

                    b.Property<string>("city")
                        .HasColumnType("text");

                    b.Property<string>("country")
                        .HasColumnType("text");

                    b.Property<double?>("lat")
                        .HasColumnType("double precision");

                    b.Property<double?>("lon")
                        .HasColumnType("double precision");

                    b.Property<string>("postal_code")
                        .HasColumnType("text");

                    b.Property<string>("region")
                        .HasColumnType("text");

                    b.Property<string>("store_number")
                        .HasColumnType("text");

                    b.Property<Guid>("transaction_id")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("transaction_id")
                        .IsUnique();

                    b.ToTable("TransactionLocation");
                });

            modelBuilder.Entity("BudgetBuddyAPI.TransactionPaymentMeta", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("by_order_of")
                        .HasColumnType("text");

                    b.Property<string>("payee")
                        .HasColumnType("text");

                    b.Property<string>("payer")
                        .HasColumnType("text");

                    b.Property<string>("payment_method")
                        .HasColumnType("text");

                    b.Property<string>("payment_processor")
                        .HasColumnType("text");

                    b.Property<string>("ppd_id")
                        .HasColumnType("text");

                    b.Property<string>("reason")
                        .HasColumnType("text");

                    b.Property<string>("reference_number")
                        .HasColumnType("text");

                    b.Property<Guid>("transaction_id")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("transaction_id")
                        .IsUnique();

                    b.ToTable("TransactionPaymentMeta");
                });

            modelBuilder.Entity("BudgetBuddyAPI.User", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Institution", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("country_codes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("institution_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("products")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("institution_id")
                        .IsUnique();

                    b.ToTable("Institutions");
                });

            modelBuilder.Entity("Transaction", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("account_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("account_owner")
                        .HasColumnType("text");

                    b.Property<decimal>("amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("authorized_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("authorized_datetime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("bank_account_id")
                        .HasColumnType("integer");

                    b.Property<string>("check_number")
                        .HasColumnType("text");

                    b.Property<DateTime>("date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("datetime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("iso_currency_code")
                        .HasColumnType("text");

                    b.Property<string>("logo_url")
                        .HasColumnType("text");

                    b.Property<string>("merchant_entity_id")
                        .HasColumnType("text");

                    b.Property<string>("merchant_name")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("payment_channel")
                        .HasColumnType("text");

                    b.Property<bool>("pending")
                        .HasColumnType("boolean");

                    b.Property<string>("pending_transaction_id")
                        .HasColumnType("text");

                    b.Property<string>("personal_finance_category_icon_url")
                        .HasColumnType("text");

                    b.Property<string>("transaction_code")
                        .HasColumnType("text");

                    b.Property<string>("transaction_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("transaction_type")
                        .HasColumnType("text");

                    b.Property<string>("unofficial_currency_code")
                        .HasColumnType("text");

                    b.Property<string>("website")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("bank_account_id");

                    b.HasIndex("transaction_id")
                        .IsUnique();

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("TransactionCounterparty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TransactionId")
                        .HasColumnType("uuid");

                    b.Property<string>("confidence_level")
                        .HasColumnType("text");

                    b.Property<string>("entity_id")
                        .HasColumnType("text");

                    b.Property<string>("logo_url")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<string>("phone_number")
                        .HasColumnType("text");

                    b.Property<string>("type")
                        .HasColumnType("text");

                    b.Property<string>("website")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId");

                    b.ToTable("TransactionCounterparty");
                });

            modelBuilder.Entity("BankConnection", b =>
                {
                    b.HasOne("Institution", "institution")
                        .WithMany("bank_connections")
                        .HasForeignKey("institution_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BudgetBuddyAPI.User", "user")
                        .WithMany("bank_connections")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("institution");

                    b.Navigation("user");
                });

            modelBuilder.Entity("BudgetBuddyAPI.BankAccount", b =>
                {
                    b.HasOne("BankConnection", "bank_connection")
                        .WithMany("accounts")
                        .HasForeignKey("bank_connection_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("AccountBalances", "balances", b1 =>
                        {
                            b1.Property<int>("BankAccountid")
                                .HasColumnType("integer");

                            b1.Property<decimal?>("available")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("current")
                                .HasColumnType("numeric");

                            b1.Property<string>("iso_currency_code")
                                .HasColumnType("text");

                            b1.Property<decimal?>("limit")
                                .HasColumnType("numeric");

                            b1.Property<string>("unofficial_currency_code")
                                .HasColumnType("text");

                            b1.HasKey("BankAccountid");

                            b1.ToTable("BankAccounts");

                            b1.WithOwner()
                                .HasForeignKey("BankAccountid");
                        });

                    b.Navigation("balances")
                        .IsRequired();

                    b.Navigation("bank_connection");
                });

            modelBuilder.Entity("BudgetBuddyAPI.TransactionLocation", b =>
                {
                    b.HasOne("Transaction", "transaction")
                        .WithOne("location")
                        .HasForeignKey("BudgetBuddyAPI.TransactionLocation", "transaction_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("transaction");
                });

            modelBuilder.Entity("BudgetBuddyAPI.TransactionPaymentMeta", b =>
                {
                    b.HasOne("Transaction", "transaction")
                        .WithOne("payment_meta")
                        .HasForeignKey("BudgetBuddyAPI.TransactionPaymentMeta", "transaction_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("transaction");
                });

            modelBuilder.Entity("Transaction", b =>
                {
                    b.HasOne("BudgetBuddyAPI.BankAccount", "bank_account")
                        .WithMany("transactions")
                        .HasForeignKey("bank_account_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BudgetBuddyAPI.Src.DB.PersonalFinanceCategory", "personal_finance_category", b1 =>
                        {
                            b1.Property<Guid>("Transactionid")
                                .HasColumnType("uuid");

                            b1.Property<string>("confidence_level")
                                .HasColumnType("text");

                            b1.Property<string>("detailed")
                                .HasColumnType("text");

                            b1.Property<string>("primary")
                                .HasColumnType("text");

                            b1.HasKey("Transactionid");

                            b1.ToTable("Transactions");

                            b1.WithOwner()
                                .HasForeignKey("Transactionid");
                        });

                    b.Navigation("bank_account");

                    b.Navigation("personal_finance_category");
                });

            modelBuilder.Entity("TransactionCounterparty", b =>
                {
                    b.HasOne("Transaction", null)
                        .WithMany("counterparties")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BankConnection", b =>
                {
                    b.Navigation("accounts");
                });

            modelBuilder.Entity("BudgetBuddyAPI.BankAccount", b =>
                {
                    b.Navigation("transactions");
                });

            modelBuilder.Entity("BudgetBuddyAPI.User", b =>
                {
                    b.Navigation("bank_connections");
                });

            modelBuilder.Entity("Institution", b =>
                {
                    b.Navigation("bank_connections");
                });

            modelBuilder.Entity("Transaction", b =>
                {
                    b.Navigation("counterparties");

                    b.Navigation("location");

                    b.Navigation("payment_meta");
                });
#pragma warning restore 612, 618
        }
    }
}
